M48
; DRILL file {KiCad 7.0.8} date Thu Jun  6 10:31:25 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-06T10:31:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,3,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.400
%
G90
G05
T1
X121.2Y-108.2
X133.3Y-105.9
X135.2Y-122.5
X136.75Y-108.15
X137.1Y-150.2
X138.5Y-147.1
X151.2Y-109.6
T0
M30
